//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sistema_Ferreteria.Database
{

    [Persistent(@"clientes")]
    public partial class Clientes : XPLiteObject
    {
        int fidCliente;
        [Key(true)]
        public int idCliente
        {
            get { return fidCliente; }
            set { SetPropertyValue<int>(nameof(idCliente), ref fidCliente, value); }
        }
        string fnombre;
        [Size(60)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fapellido;
        [Size(60)]
        public string apellido
        {
            get { return fapellido; }
            set { SetPropertyValue<string>(nameof(apellido), ref fapellido, value); }
        }
        string fcedula;
        [Size(20)]
        public string cedula
        {
            get { return fcedula; }
            set { SetPropertyValue<string>(nameof(cedula), ref fcedula, value); }
        }
        string ftelefono;
        [Size(15)]
        public string telefono
        {
            get { return ftelefono; }
            set { SetPropertyValue<string>(nameof(telefono), ref ftelefono, value); }
        }
        string femail;
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fdireccion;
        [Size(SizeAttribute.Unlimited)]
        public string direccion
        {
            get { return fdireccion; }
            set { SetPropertyValue<string>(nameof(direccion), ref fdireccion, value); }
        }
        DateTime ffechaRegistro;
        public DateTime fechaRegistro
        {
            get { return ffechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(fechaRegistro), ref ffechaRegistro, value); }
        }
        bool factivo;
        public bool activo
        {
            get { return factivo; }
            set { SetPropertyValue<bool>(nameof(activo), ref factivo, value); }
        }
        [Association(@"VentasReferencesClientes")]
        public XPCollection<Ventas> VentasCollection { get { return GetCollection<Ventas>(nameof(VentasCollection)); } }
    }

}
