//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sistema_Ferreteria.Database
{

    [Persistent(@"detalles_venta")]
    public partial class DetallesVenta : XPLiteObject
    {
        int fidDetalleVenta;
        [Key(true)]
        public int idDetalleVenta
        {
            get { return fidDetalleVenta; }
            set { SetPropertyValue<int>(nameof(idDetalleVenta), ref fidDetalleVenta, value); }
        }
        Ventas fventa;
        [Association(@"DetallesVentaReferencesVentas")]
        public Ventas venta
        {
            get { return fventa; }
            set { SetPropertyValue<Ventas>(nameof(venta), ref fventa, value); }
        }
        Productos fproducto;
        [Association(@"DetallesVentaReferencesProductos")]
        public Productos producto
        {
            get { return fproducto; }
            set { SetPropertyValue<Productos>(nameof(producto), ref fproducto, value); }
        }
        int fcantidad;
        public int cantidad
        {
            get { return fcantidad; }
            set { SetPropertyValue<int>(nameof(cantidad), ref fcantidad, value); }
        }
        double fsubtotal;
        public double subtotal
        {
            get { return fsubtotal; }
            set { SetPropertyValue<double>(nameof(subtotal), ref fsubtotal, value); }
        }
        double fprecio;
        public double precio
        {
            get { return fprecio; }
            set { SetPropertyValue<double>(nameof(precio), ref fprecio, value); }
        }
    }

}
