//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sistema_Ferreteria.Database
{

    [Persistent(@"entrada_productos")]
    public partial class EntradaProductos : XPLiteObject
    {
        int fidEntradaProductos;
        [Key(true)]
        public int idEntradaProductos
        {
            get { return fidEntradaProductos; }
            set { SetPropertyValue<int>(nameof(idEntradaProductos), ref fidEntradaProductos, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        int fcantidad;
        public int cantidad
        {
            get { return fcantidad; }
            set { SetPropertyValue<int>(nameof(cantidad), ref fcantidad, value); }
        }
        double fprecioCompra;
        public double precioCompra
        {
            get { return fprecioCompra; }
            set { SetPropertyValue<double>(nameof(precioCompra), ref fprecioCompra, value); }
        }
        double fimporte;
        public double importe
        {
            get { return fimporte; }
            set { SetPropertyValue<double>(nameof(importe), ref fimporte, value); }
        }
        Productos fproducto;
        [Association(@"EntradaProductosReferencesProductos")]
        public Productos producto
        {
            get { return fproducto; }
            set { SetPropertyValue<Productos>(nameof(producto), ref fproducto, value); }
        }
    }

}
