//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sistema_Ferreteria.Database
{

    [Persistent(@"roles")]
    public partial class Roles : XPLiteObject
    {
        int fidRol;
        [Key(true)]
        public int idRol
        {
            get { return fidRol; }
            set { SetPropertyValue<int>(nameof(idRol), ref fidRol, value); }
        }
        string frol;
        [Size(30)]
        public string rol
        {
            get { return frol; }
            set { SetPropertyValue<string>(nameof(rol), ref frol, value); }
        }
        string fdescripcion;
        [Size(SizeAttribute.Unlimited)]
        public string descripcion
        {
            get { return fdescripcion; }
            set { SetPropertyValue<string>(nameof(descripcion), ref fdescripcion, value); }
        }
        [Association(@"UsuariosReferencesRoles")]
        public XPCollection<Usuarios> UsuariosCollection { get { return GetCollection<Usuarios>(nameof(UsuariosCollection)); } }
    }

}
