//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sistema_Ferreteria.Database
{

    [Persistent(@"usuarios")]
    public partial class Usuarios : XPLiteObject
    {
        int fidUsuario;
        [Key(true)]
        public int idUsuario
        {
            get { return fidUsuario; }
            set { SetPropertyValue<int>(nameof(idUsuario), ref fidUsuario, value); }
        }
        string fusuario;
        [Size(30)]
        public string usuario
        {
            get { return fusuario; }
            set { SetPropertyValue<string>(nameof(usuario), ref fusuario, value); }
        }
        string fnombre;
        [Size(60)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fapellido;
        [Size(60)]
        public string apellido
        {
            get { return fapellido; }
            set { SetPropertyValue<string>(nameof(apellido), ref fapellido, value); }
        }
        string fcedula;
        [Size(20)]
        public string cedula
        {
            get { return fcedula; }
            set { SetPropertyValue<string>(nameof(cedula), ref fcedula, value); }
        }
        string ftelefono;
        [Size(15)]
        public string telefono
        {
            get { return ftelefono; }
            set { SetPropertyValue<string>(nameof(telefono), ref ftelefono, value); }
        }
        string femail;
        [Indexed(Name = @"email", Unique = true)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fpassword;
        [Size(255)]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>(nameof(password), ref fpassword, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        bool factivo;
        public bool activo
        {
            get { return factivo; }
            set { SetPropertyValue<bool>(nameof(activo), ref factivo, value); }
        }
        Roles frol;
        [Association(@"UsuariosReferencesRoles")]
        public Roles rol
        {
            get { return frol; }
            set { SetPropertyValue<Roles>(nameof(rol), ref frol, value); }
        }
        [Association(@"VentasReferencesUsuarios")]
        public XPCollection<Ventas> VentasCollection { get { return GetCollection<Ventas>(nameof(VentasCollection)); } }
    }

}
