//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Sistema_Ferreteria.Database
{

    [Persistent(@"ventas")]
    public partial class Ventas : XPLiteObject
    {
        int fidVenta;
        [Key(true)]
        public int idVenta
        {
            get { return fidVenta; }
            set { SetPropertyValue<int>(nameof(idVenta), ref fidVenta, value); }
        }
        DateTime ffecha;
        public DateTime fecha
        {
            get { return ffecha; }
            set { SetPropertyValue<DateTime>(nameof(fecha), ref ffecha, value); }
        }
        double ftotal;
        public double total
        {
            get { return ftotal; }
            set { SetPropertyValue<double>(nameof(total), ref ftotal, value); }
        }
        Clientes fcliente;
        [Association(@"VentasReferencesClientes")]
        public Clientes cliente
        {
            get { return fcliente; }
            set { SetPropertyValue<Clientes>(nameof(cliente), ref fcliente, value); }
        }
        Usuarios fusuario;
        [Association(@"VentasReferencesUsuarios")]
        public Usuarios usuario
        {
            get { return fusuario; }
            set { SetPropertyValue<Usuarios>(nameof(usuario), ref fusuario, value); }
        }
        [Association(@"DetallesVentaReferencesVentas")]
        public XPCollection<DetallesVenta> DetallesVentas { get { return GetCollection<DetallesVenta>(nameof(DetallesVentas)); } }
    }

}
